/*
 * Copyright 2018 The Embulk Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.embulk.deps.classloaders;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.JarURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.net.URLStreamHandler;
import java.net.UnknownServiceException;
import java.util.jar.JarEntry;
import java.util.jar.JarInputStream;

/**
 * Generates a special URL for a resource in JAR in JAR, which is coupled with its special URLStreamHandler.
 *
 * <p>Such URLs are required when {@code getResource} is called to get a URL of a resource in JAR in JAR.
 *
 * @see <a href="https://www.ibm.com/developerworks/library/j-onejar/#N101E7">Simplify your application delivery with One-JAR</a>
 */
@SuppressWarnings("checkstyle:AbbreviationAsWordInName")
class NestedSpecialURLFactory {
    private NestedSpecialURLFactory(final URL topLevelJarFileUrl, final String specialProtocol) {
        this.topLevelJarFileUrl = topLevelJarFileUrl;
        this.specialProtocol = specialProtocol;

        this.urlStreamHandler = new SpecialURLStreamHandler();
    }

    /**
     * Creates a factory instance that generates special URLs of resources in JAR in JAR with the given protocol.
     *
     * <p>A generated URL is like "(specialProtocol):jar:file:....jar!/....jar!/...".
     *
     * @param topLevelJarFileUrl  a URL instance whose protocol is "jar:file:"
     * @param specialProtocol  protocol of special URLs generated by the factory
     * @return the factory instance created
     */
    @SuppressWarnings("checkstyle:AbbreviationAsWordInName")
    static NestedSpecialURLFactory ofJarFileURL(
            final URL topLevelJarFileUrl,
            final String specialProtocol)
            throws MalformedURLException {
        // Given |topLevelJarFileUrl| must be a "jar:file:" URL such as "jar:file:///path/to/top.jar!/".
        // See Javadoc of JarURLConnection: https://docs.oracle.com/javase/8/docs/api/java/net/JarURLConnection.html
        if (!"jar".equals(topLevelJarFileUrl.getProtocol())) {
            throw new MalformedURLException(String.format("Invalid URL: protocol must be \"jar:file:....jar!/\": %s",
                                                          topLevelJarFileUrl.toString()));
        }

        final String topLevelJarFileUrlPath = topLevelJarFileUrl.getPath();
        if (!topLevelJarFileUrlPath.endsWith("!/")) {
            throw new MalformedURLException(String.format("Invalid URL: protocol must be \"jar:file:....jar!/\": %s",
                                                          topLevelJarFileUrl.toString()));
        }
        final URL topLevelFileUrl;
        try {
            topLevelFileUrl = new URL(topLevelJarFileUrlPath);
        } catch (MalformedURLException ex) {
            throw new MalformedURLException(String.format("Invalid URL: protocol must be \"jar:file:....jar!/\": %s",
                                                          topLevelJarFileUrl.toString()));
        }
        if (!"file".equals(topLevelFileUrl.getProtocol())) {
            throw new MalformedURLException(String.format("Invalid URL: protocol must be \"jar:file:....jar!/\": %s",
                                                          topLevelJarFileUrl.toString()));
        }

        return new NestedSpecialURLFactory(topLevelJarFileUrl, specialProtocol);
    }

    /**
     * Creates a factory instance that generates special URLs of resources in JAR in JAR with the given protocol.
     *
     * <p>A generated URL is like "(specialProtocol):jar:file:....jar!/....jar!/...".
     *
     * @param topLevelFileUrl  a URL instance whose protocol is "file:"
     * @param specialProtocol  protocol of special URLs generated by the factory
     * @return the factory instance created
     */
    @SuppressWarnings("checkstyle:AbbreviationAsWordInName")
    static NestedSpecialURLFactory ofFileURL(
            final URL topLevelFileUrl,
            final String specialProtocol)
            throws MalformedURLException {
        // Given |topLevelFileUrl| must be a "file:" URL such as "file:///path/to/top.jar".
        if (!"file".equals(topLevelFileUrl.getProtocol())) {
            throw new MalformedURLException(
                    String.format("Invalid URL: protocol must be \"file:\": %s", topLevelFileUrl.toString()));
        }

        // Creates a "jar:file:" URL such as "jar:file:///path/to/top.jar!/".
        // See Javadoc of JarURLConnection: https://docs.oracle.com/javase/8/docs/api/java/net/JarURLConnection.html
        final URL topLevelJarFileUrl = new URL("jar", "", -1, topLevelFileUrl.toString() + "!/");

        return new NestedSpecialURLFactory(topLevelJarFileUrl, specialProtocol);
    }

    /**
     * Creates a factory instance that generates special URLs of resources in JAR in JAR with "jar:" protocol.
     *
     * <p>Note that a generated URL is strange like "jar:jar:file:....jar!/....jar!/...".
     * Such a strange URL may cause problems depending on how the URL is processed. Just calling
     * its {@code openConnection} and {@code openStream} should work as they are correctly handled
     * by {@code URLStreamHandler} which is coupled with the {@code URL} instance by this factory,
     *
     * @param topLevelFileUrl  URL instance whose protocol is "file:"
     * @return factory instance created
     */
    @SuppressWarnings("checkstyle:AbbreviationAsWordInName")
    static NestedSpecialURLFactory ofFileURL(
            final URL topLevelFileUrl)
            throws MalformedURLException {
        return ofFileURL(topLevelFileUrl, "jar");
    }

    /**
     * Generates a special URL instance.
     *
     * @param resourceNameOfJarInJar  Resource name of the JAR file contained in the top-level JAR
     * @param resourceNameInJarInJar  Name of the resource in the JAR specified by {@code resourceNameOfJarInJar}
     * @return URL instance generated
     */
    URL create(
            final String resourceNameOfJarInJar,
            final String resourceNameInJarInJar)
            throws MalformedURLException {
        // Creates a "jar:file:" URL such as "jar:file:///path/to/top.jar!/another/path/to/contained.jar".
        final URL urlOfJarInJar = new URL(
                this.topLevelJarFileUrl,
                resourceNameOfJarInJar.startsWith("/") ? resourceNameOfJarInJar.substring(1) : resourceNameOfJarInJar);

        // Creates a final "special:jar:file:" URL such as
        //
        //   "special:jar:file:///path/to/top.jar!/another/path/to/contained.jar!/more/path/to/resource.file"
        //
        // with URLStreamHandler coupled to process it into InputStream.
        return new URL(
                this.specialProtocol,
                "",
                -1,
                urlOfJarInJar.toString()
                        + "!" + (resourceNameInJarInJar.startsWith("/") ? "" : "/")
                        + resourceNameInJarInJar,
                this.urlStreamHandler);
    }

    /**
     * Special URLStreamHandler to be coupled with URLs created by NestedSpecialURLFactory.
     *
     * <p>Its URL handling is specifically coupled with how {@code NestedSpecialURLFactory#create} builds a URL.
     * This class should be {@code private} so that it is not used apart from {@code NestedSpecialURLFactory}.
     */
    @SuppressWarnings("checkstyle:AbbreviationAsWordInName")
    private class SpecialURLStreamHandler extends URLStreamHandler {
        @Override
        protected URLConnection openConnection(final URL url) throws IOException {
            // Note that declaring variables here may cause unexpected behaviors.
            // https://stackoverflow.com/questions/9952815/s3-java-client-fails-a-lot-with-premature-end-of-content-length-delimited-messa
            return new URLConnection(url) {
                @Override
                public void connect() {
                    // Do nothing.
                }

                /**
                 * Breaks down the special URL built by NestedSpecialURLFactory, and creates InputStream to read from.
                 */
                @Override
                public InputStream getInputStream() throws IOException {
                    final URL specialUrlOfResourceInJarInJar = getURL();
                    if (!specialUrlOfResourceInJarInJar.getProtocol().equals(specialProtocol)) {
                        throw new IOException(String.format(
                                "FATAL: Unexpected URL is coupled with URLStreamHandler: \"%s\" is against \"%s\"",
                                specialUrlOfResourceInJarInJar,
                                specialProtocol));
                    }

                    // Extracts "jar:file:///path/to/top.jar!/path2/to/contained.jar!/path3/to/resource.file"
                    // from "special:jar:file:///path/to/top.jar!/path2/to/contained.jar!/path3/to/resource.file"
                    final String urlOfJarInJarWithResource = specialUrlOfResourceInJarInJar.getPath();

                    final int indexOfLastSeparator = urlOfJarInJarWithResource.lastIndexOf("!/");
                    if (indexOfLastSeparator < 0) {
                        throw new IOException(
                                String.format("FATAL: No resource separator in URL: \"%s\"",
                                              specialUrlOfResourceInJarInJar));
                    }

                    // Breaks "jar:file:///path/to/top.jar!/path2/to/contained.jar!/path3/to/resource.file" down into
                    // 1. "jar:file:///path/to/top.jar!/path2/to/contained.jar"
                    // 2. "path3/to/resource.file"
                    //
                    // Note that the intermediate slash ('/') is dropped.
                    final URL urlOfJarInJar = new URL(urlOfJarInJarWithResource.substring(0, indexOfLastSeparator));
                    final String resourceNameInJarInJar = urlOfJarInJarWithResource.substring(indexOfLastSeparator + 2);

                    // Opens a URLConnection from "jar:file:///path/to/top.jar!/path2/to/contained.jar"
                    //
                    // Note that the Connection is released once the InputStream (below) is closed.
                    //
                    // "Invoking the close() methods on the InputStream or OutputStream of an URLConnection after a
                    // request may free network resources associated with this instance, unless particular protocol
                    // specifications specify different behaviours for it."
                    // See: https://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html
                    final JarURLConnection jarInJarConnection;
                    try {
                        final URLConnection urlConnection = urlOfJarInJar.openConnection();
                        jarInJarConnection = (JarURLConnection) urlConnection;
                    } catch (IOException ex) {
                        throw new IOException(
                                String.format("Failed to open a JAR resource in JAR: \"%s\"",
                                              urlOfJarInJar), ex);
                    } catch (ClassCastException ex) {
                        throw new IOException(
                                String.format("FATAL: URLConnection from \"%s\" URL is not JarURLConnection.",
                                              urlOfJarInJar), ex);
                    }

                    // Gets InputStream from "jar:file:///path/to/top.jar!/path2/to/contained.jar"
                    final InputStream inputStreamFromJarInJar;
                    try {
                        inputStreamFromJarInJar = jarInJarConnection.getInputStream();
                    } catch (UnknownServiceException ex) {
                        throw new IOException(
                                String.format("FATAL: Input from URL \"%s\" is unexpectedly not supported.",
                                              urlOfJarInJar), ex);
                    } catch (IOException ex) {
                        throw new IOException(
                                String.format("Failed to read a JAR resource in JAR: \"%s\"",
                                              urlOfJarInJar), ex);
                    }

                    // Parses "jar:file:///path/to/top.jar!/path2/to/contained.jar" as a JAR
                    final JarInputStream jarInputStreamFromJarInJar;
                    try {
                        jarInputStreamFromJarInJar = new JarInputStream(inputStreamFromJarInJar);
                    } catch (IOException ex) {
                        throw new IOException(
                                String.format("Failed in parsing a JAR resource in JAR: \"%s\"",
                                              urlOfJarInJar), ex);
                    }

                    // Looks for "/path3/to/resource.file" in "jar:file:///path/to/top.jar!/path2/to/contained.jar"
                    JarEntry jarEntry;
                    try {
                        jarEntry = jarInputStreamFromJarInJar.getNextJarEntry();
                    } catch (IOException ex) {
                        throw new IOException(
                                String.format("Failed in reading a resource in JAR in JAR: \"%s\"",
                                              urlOfJarInJar), ex);
                    }
                    while (jarEntry != null) {
                        if (jarEntry.getName().equals(resourceNameInJarInJar)) {
                            // |jarInputStreamFromJarInJar| points "/path3/to/resource.file" at the moment.
                            return jarInputStreamFromJarInJar;
                        }
                        try {
                            jarEntry = jarInputStreamFromJarInJar.getNextJarEntry();
                        } catch (IOException ex) {
                            throw new IOException(
                                    String.format("Failed in reading a resource in JAR in JAR: \"%s\"",
                                                  urlOfJarInJar), ex);
                        }
                    }
                    throw new FileNotFoundException(
                            String.format("Resource in JAR in JAR is not found: \"%s\" in \"%s\"",
                                          resourceNameInJarInJar,
                                          urlOfJarInJar));
                }
            };
        }
    }

    private final URL topLevelJarFileUrl;
    private final String specialProtocol;

    private final SpecialURLStreamHandler urlStreamHandler;
}
